ci:  add required check for linting CI (#10263)
refactor:  lint required check

diff --git a/.github/workflows/ci-lint.yaml b/.github/workflows/ci-lint.yaml
--- a/.github/workflows/ci-lint.yaml
+++ b/.github/workflows/ci-lint.yaml
@@ -120,3 +120,23 @@ jobs:
         uses: ./.github/actions/pnpm/install-dependencies
         with:
           frozen-lockfile: true
+  lint_required_check:
+    # this job will be used for GitHub actions to determine required job success or not;
+    # When code changed, it will check if any of the test jobs failed.
+    # When *only* doc changed, it will run as success directly
+    name: Lint Required Check
+    needs: [ lint, lint-website, check-changed, spell, pnpm_lockfile_check ]
+    if: ${{ always() && !cancelled() }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Log
+        run: echo ${{ join(needs.*.result, ',') }}
+      - name: Code Lint check
+        if: ${{ needs.check-changed.outputs.code_changed == 'true'  &&
+          needs.lint.result != 'success'
+          }}
+        run: echo "Code Lint Failed" && exit 1
+      - name: Doc Lint Check
+        if: ${{ needs.check-changed.outputs.document_changed == 'true' 
+          && needs.lint-website.result != 'success'}}
+        run: echo "Website Lint Failed" && exit 1
