chore(ci): run size limit on main (#13740)
* refactor: run size limit on main

* fix:fixing typos.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -207,21 +207,20 @@ jobs:
         if: ${{ needs.check-changed.outputs.code_changed == 'true'
           && github.event_name == 'pull_request'
           && join(needs.*.result, ',')!='success,success,success,success,success,success,success,success,success,success' }}
-        run: echo "Tess Failed" && exit 1
+        run: echo "Test Failed" && exit 1
 
       - name: Test check
         if: ${{ needs.check-changed.outputs.code_changed == 'true'
           && github.event_name != 'pull_request'
-          && join(needs.*.result, ',')!='success,success,success,success,success,success,success,success,skipped,success' }}
-        run: echo "Tess Failed" && exit 1
+          && join(needs.*.result, ',')!='success,success,success,success,success,success,success,success,success,success' }}
+        run: echo "Test Failed" && exit 1
 
       - name: No check to Run test
         run: echo "Success"
 
   size-limit:
     name: Binary Size Limit
-    needs: [check-changed, build-linux]
-    if: ${{ needs.check-changed.outputs.code_changed == 'true' && github.event_name == 'pull_request' }}
+    needs: [build-linux]
     uses: ./.github/workflows/size-limit.yml
 
   ecosystem_ci_per_commit:
