revert: ⏪ windows only

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,14 +30,86 @@ permissions:
   issues: write
 
 jobs:
+  check-changed:
+    runs-on: ubuntu-latest
+    name: Check Source Changed
+    outputs:
+      code_changed: ${{ steps.filter.outputs.code_changed == 'true' }}
+      document_changed: ${{ steps.filter.outputs.document_changed == 'true' }}
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
+      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
+        id: filter
+        with:
+          predicate-quantifier: "every"
+          filters: |
+            code_changed:
+              - "!**/*.md"
+              - "!**/*.mdx"
+              - "!website/**"
+            document_changed:
+              - "website/**"
+
+  test-linux:
+    name: Test Linux
+    needs: [check-changed]
+    if: ${{ needs.check-changed.outputs.code_changed == 'true' }}
+    uses: ./.github/workflows/reusable-build.yml
+    with:
+      target: x86_64-unknown-linux-gnu
+      runner: ${{ vars.LINUX_SELF_HOSTED_RUNNER_LABELS || '"ubuntu-22.04"' }}
+      test: true
+      bench: true
+
   test-windows:
     name: Test Windows
+    needs: [check-changed]
+    if: ${{ needs.check-changed.outputs.code_changed == 'true' }}
     uses: ./.github/workflows/reusable-build.yml
     with:
       target: x86_64-pc-windows-msvc
       profile: "dev"
       runner: ${{ vars.WINDOWS_SELF_HOSTED_RUNNER_LABELS || '"windows-latest"' }}
       test: true
+
+  test-mac:
+    name: Test Mac ARM64
+    needs: [check-changed]
+    if: ${{ needs.check-changed.outputs.code_changed == 'true' }}
+    uses: ./.github/workflows/reusable-build.yml
+    with:
+      target: aarch64-apple-darwin
+      profile: "ci"
+      runner: ${{ vars.MACOS_RUNNER_LABELS || '"macos-latest"' }}
+      test: true
+
+  test-wasm:
+    name: Test WASM
+    needs: [check-changed]
+    if: ${{ needs.check-changed.outputs.code_changed == 'true' }}
+    uses: ./.github/workflows/reusable-build.yml
+    with:
+      target: wasm32-wasip1-threads
+      profile: "ci"
+      runner: ${{ vars.LINUX_SELF_HOSTED_RUNNER_LABELS || '"ubuntu-22.04"' }}
+      test: false
+
+  test_required_check:
+    # this job will be used for GitHub actions to determine required job success or not;
+    # When code changed, it will check if any of the test jobs failed.
+    # When *only* doc changed, it will run as success directly
+    name: Test Required Check
+    needs: [test-linux, test-windows, test-mac, check-changed]
+    if: ${{ always() && !cancelled() }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Log
+        run: echo ${{ join(needs.*.result, ',') }}
+      - name: Test check
+        if: ${{ needs.check-changed.outputs.code_changed == 'true' && join(needs.*.result, ',')!='success,success,success,success' }}
+        run: echo "Tess Failed" && exit 1
+      - name: No check to Run test
+        run: echo "Success"
 
   # TODO: enable it after self hosted runners are ready
   # pkg-preview:
