fix:fixing typos.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -207,13 +207,13 @@ jobs:
         if: ${{ needs.check-changed.outputs.code_changed == 'true'
           && github.event_name == 'pull_request'
           && join(needs.*.result, ',')!='success,success,success,success,success,success,success,success,success,success' }}
-        run: echo "Tess Failed" && exit 1
+        run: echo "Test Failed" && exit 1
 
       - name: Test check
         if: ${{ needs.check-changed.outputs.code_changed == 'true'
           && github.event_name != 'pull_request'
           && join(needs.*.result, ',')!='success,success,success,success,success,success,success,success,success,success' }}
-        run: echo "Tess Failed" && exit 1
+        run: echo "Test Failed" && exit 1
 
       - name: No check to Run test
         run: echo "Success"
