chore: 🤖 comment some unnecessary platform

diff --git a/.github/workflows/test-pr.yml b/.github/workflows/test-pr.yml
--- a/.github/workflows/test-pr.yml
+++ b/.github/workflows/test-pr.yml
@@ -35,13 +35,13 @@ jobs:
               sudo apt-get -y install protobuf-compiler
               RUST_TARGET=x86_64-unknown-linux-gnu pnpm build:binding:release
               strip crates/node_binding/*.node
-          - host: ubuntu-latest
-            target: x86_64-unknown-linux-musl
-            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
-            build: |
-              apk add --no-cache protoc
-              RUST_TARGET=x86_64-unknown-linux-musl pnpm build:binding:release
-              strip crates/node_binding/*.node
+          # - host: ubuntu-latest
+          #   target: x86_64-unknown-linux-musl
+          #   docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
+          #   build: |
+          #     apk add --no-cache protoc
+          #     RUST_TARGET=x86_64-unknown-linux-musl pnpm build:binding:release
+          #     strip crates/node_binding/*.node
           - host: windows-latest
             target: x86_64-pc-windows-msvc
             build: |
@@ -179,39 +179,39 @@ jobs:
             pnpm --filter @rspack/core run test
             pnpm --filter @rspack/dev-server run test
             pnpm --filter @rspack/plugin-html run test
-  test-x86_64-unknown-linux-musl:
-    strategy:
-      fail-fast: false
-      matrix:
-        node:
-          - "14"
-          - "16"
-    runs-on: ubuntu-latest
-    needs:
-      - build
-    steps:
-      - uses: actions/checkout@v3
-      - name: Download bindings
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-x86_64-unknown-linux-musl
-          path: crates/node_binding/
-      - name: Show restored binding
-        run: ls -lah crates/node_binding/*.node
-      - name: Run tests
-        uses: addnab/docker-run-action@v3
-        with:
-          image: node:${{ matrix.node }}-alpine
-          options: -v ${{ github.workspace }}:/build -w /build
-          run: |
-            set -e
-            npm install -g pnpm@7.25.0
-            pnpm install
-            pnpm run build:js
+  # test-x86_64-unknown-linux-musl:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       node:
+  #         - "14"
+  #         - "16"
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - build
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - name: Download bindings
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: bindings-x86_64-unknown-linux-musl
+  #         path: crates/node_binding/
+  #     - name: Show restored binding
+  #       run: ls -lah crates/node_binding/*.node
+  #     - name: Run tests
+  #       uses: addnab/docker-run-action@v3
+  #       with:
+  #         image: node:${{ matrix.node }}-alpine
+  #         options: -v ${{ github.workspace }}:/build -w /build
+  #         run: |
+  #           set -e
+  #           npm install -g pnpm@7.25.0
+  #           pnpm install
+  #           pnpm run build:js
 
-            pnpm --filter @rspack/core run test
-            pnpm --filter @rspack/dev-server run test
-            pnpm --filter @rspack/plugin-html run test
+  #           pnpm --filter @rspack/core run test
+  #           pnpm --filter @rspack/dev-server run test
+  #           pnpm --filter @rspack/plugin-html run test
   test-x86_64-apple-darwin:
     strategy:
       fail-fast: false
